# Generated by Django 5.1.7 on 2025-03-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
