# Generated by Django 5.1.7 on 2025-03-26 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('formation_structure', models.CharField(help_text="Format: e.g. '4-4-2', '4-3-3', etc.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineupPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('position_type', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_template', models.BooleanField(default=False, help_text='Is this a reusable template lineup?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lineups', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teammanager.formationtemplate')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='teammanager.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='teammanager.team')),
            ],
        ),
        migrations.CreateModel(
            name='LineupPlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=2, help_text='X coordinate on pitch (0-100)', max_digits=5)),
                ('y_coordinate', models.DecimalField(decimal_places=2, help_text='Y coordinate on pitch (0-100)', max_digits=5)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_starter', models.BooleanField(default=True, help_text='Is this player in the starting lineup?')),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_positions', to='teammanager.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_positions', to='teammanager.player')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teammanager.lineupposition')),
            ],
            options={
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
