# Generated by Django 5.1.7 on 2025-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0005_formationtemplate_lineupposition_lineup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationtemplate',
            name='player_count',
            field=models.PositiveSmallIntegerField(choices=[(5, '5-a-side'), (7, '7-a-side'), (9, '9-a-side'), (11, '11-a-side')], default=7, help_text='Select the number of players for this formation'),
        ),
    ]
