# Generated by Django 5.1.7 on 2025-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0007_alter_formationtemplate_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='direction',
            field=models.CharField(choices=[('LR', 'First Period (GK Left)'), ('RL', 'Second Period (GK Right)')], default='LR', help_text='Direction of play (LR=GK on left, RL=GK on right)', max_length=2),
        ),
    ]
