# Generated by Django 5.1.7 on 2025-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0009_alter_lineup_direction_matchsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsession',
            name='current_period',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current period of the match'),
        ),
        migrations.AddField(
            model_name='matchsession',
            name='elapsed_time',
            field=models.PositiveIntegerField(default=0, help_text='Elapsed time in seconds from previous periods'),
        ),
    ]
