# Generated by Django 5.1.7 on 2025-03-28 06:31

import django.db.models.deletion
import teammanager.models_video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0010_matchsession_current_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=teammanager.models_video.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_reels', to='teammanager.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to=teammanager.models_video.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_minute', models.PositiveIntegerField(default=0, help_text='Minute in the game when this happened')),
                ('period', models.PositiveIntegerField(default=1, help_text='Period number when this happened')),
                ('action_tag', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('save', 'Save'), ('tackle', 'Tackle'), ('skill', 'Skill Move'), ('pass', 'Great Pass'), ('shot', 'Shot'), ('other', 'Other')], default='other', max_length=20)),
                ('is_highlight', models.BooleanField(default=True, help_text='Include in highlight reels')),
                ('match_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='teammanager.matchsession')),
                ('players_involved', models.ManyToManyField(related_name='video_appearances', to='teammanager.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HighlightClipAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlight_reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_associations', to='teammanager.highlightreel')),
                ('video_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_appearances', to='teammanager.videoclip')),
            ],
            options={
                'ordering': ['highlight_reel', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['match_session'], name='teammanager_match_s_639456_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['action_tag'], name='teammanager_action__a62a10_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['is_highlight'], name='teammanager_is_high_a91432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='highlightclipassociation',
            unique_together={('highlight_reel', 'order'), ('highlight_reel', 'video_clip')},
        ),
    ]
